# -*- coding: utf-8 -*-
"""NLP-Sentiment-Analysisassignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdMTh8tmTAEItT9VunFHeRAWNiBYs1fO

#**Product: Amazon Alexa**

## **Assignment Natural Language processsing - Sentiment Analysis**

### **Customer Review Classification using Random Forest**

- Dataset consists of 3000 Amazon customer reviews, star ratings, date of review, variant and feedback of various amazon Alexa products like Alexa Echo, Echo dots.
- **The objective is to discover insights into consumer reviews and perfrom sentiment analysis on the data.** Positive or Negative review?
- Dataset: www.kaggle.com/sid321axn/amazon-alexa-reviews also provided(`amazon_alexa.tsv`)
---




### **Follow the instructions and complete each TODO to complete the assessment on the essential steps in building and evaluating a classification model.**



**Dataset Information:**

The dataset consists of customer reviews for Amazon Alexa products, including various features related to the product variation, customer rating, and feedback sentiment.

_Features/Columns_:
* rating: The customer rating of the product (scale of 1 to 5).
* date: The date when the review was posted.
* variation: The variation or type of Alexa product the review is for (e.g., "Charcoal Fabric", "Walnut Finish").
* verified_reviews: The actual review text written by the customer.
* feedback: The target variable indicating the sentiment of the review (1 for positive sentiment and 0 for negative sentiment).



---
"""

# Amazon Alexa Customer Review Sentiment Analysis
# Objective: Classify reviews as positive or negative using Random Forest




# TODO: Import necessary libraries
# Hint: You'll need pandas, numpy, matplotlib, seaborn, and various sklearn modules

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# TODO: Load the dataset
# Hint: Use pandas to read the CSV file from your Google Drive

# Data Visualization and Clean Up
# TODO: Visualize the distribution of feedback
# Hint: Use seaborn's countplot function

# TODO: Visualize the relationship between variations and ratings
# Hint: Use seaborn's barplot function

# TODO: Drop irrelevant columns
# Hint: Use the drop() method to remove 'date' and 'rating' columns

# One-Hot Encoding
# TODO: Perform one-hot encoding on the 'variation' column
# Hint: Use pandas get_dummies() function

# Tokenization (Count Vectorizer)
# TODO: Tokenize the 'verified_reviews' column
# Hint: Use CountVectorizer from sklearn.feature_extraction.text

# TODO: Combine tokenized reviews with the main dataframe
# Hint: Use pd.concat() to join the dataframes

# Prepare data for modeling
# TODO: Split the data into features (X) and target (y)
# Hint: The target variable is 'feedback'

# : Split the data into training and testing sets
# Hint: Use train_test_split from sklearn.model_selection
TODO
# Train the Random Forest model
# TODO: Create and train the Random Forest model
# Hint: Use RandomForestClassifier from sklearn.ensemble

# Evaluate the model
# TODO: Generate predictions and create confusion matrix
# Hint: Use the predict() method and confusion_matrix from sklearn.metrics

# TODO: Plot confusion matrix
# Hint: Use seaborn's heatmap function

# TODO: Print classification report
# Hint: Use classification_report from sklearn.metrics

# Feature Importance
# TODO: Visualize feature importance
# Hint: Access feature_importances_ attribute of the trained model

# TODO: Make predictions on new data
# Hint: Create a function that takes a new review text, preprocesses it,
# and uses the trained model to predict its sentiment

# Example usage of your prediction function:
# new_review = "I love my Alexa device! It's so helpful."
# predicted_sentiment = predict_sentiment(new_review)
# print(f"The sentiment of the new review is: {predicted_sentiment}")

"""STEP 1: Import Libraries

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

"""# Mount Google Drive

"""

drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

"""Load the dataset
Use pandas to read the CSV file from your Google Drive

"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/amazon_alexa.tsv', sep='\t')

df.head()

"""# Data Visualization and Clean Up
Visualize the distribution of feedback
# Hint: Use seaborn's countplot function
"""

sns.countplot(x='feedback', data=df)
plt.title("Distribution of Feedback (Positive vs Negative)")
plt.show()

"""This visualization represents the distribution of customer feedback in the dataset using a count plot. The values 1 and 0 correspond to positive and negative reviews, respectively. The chart clearly shows that the majority of reviews are positive, indicating a strong class imbalance in the dataset. This imbalance may impact the performance of machine learning models, as they may become biased toward predicting the majority class (positive reviews). Therefore, special attention may be required during model evaluation to ensure reliable results.

Visualize the relationship between variations and ratings
# Hint: Use seaborn's barplot function
"""

plt.figure(figsize=(10,5))
sns.countplot(x='variation', hue='feedback', data=df)
plt.title("Product Variation vs Feedback")
plt.xticks(rotation=45)
plt.show()

"""This visualization compares customer feedback across different product variations using a grouped count plot. Each product variation is displayed along the x-axis, while the count of reviews is shown on the y-axis, with colors distinguishing positive (1) and negative (0) feedback. The chart reveals that all product variations receive predominantly positive reviews, indicating high customer satisfaction across the product range. Negative feedback is minimal for all variations, and no product appears to perform poorly. Additionally, certain variations have a higher number of reviews, suggesting they are more popular among customers.

Drop irrelevant columns
# Hint: Use the drop() method to remove 'date' and 'rating' columns
"""

df = df.drop(['date', 'rating'], axis=1)
df.head()

"""One-Hot Encoding
 Perform one-hot encoding on the 'variation' column
# Hint: Use pandas get_dummies() function
"""

df['verified_reviews'] = df['verified_reviews'].fillna("")

variation_dummies = pd.get_dummies(df['variation'], drop_first=True)

df = pd.concat([df, variation_dummies], axis=1)

df.drop(['variation'], axis=1, inplace=True)

df.head()

"""# Tokenization (Count Vectorizer)
 Tokenize the 'verified_reviews' column
 Use CountVectorizer from sklearn.feature_extraction.text

"""

vectorizer = CountVectorizer()

X_text = vectorizer.fit_transform(df['verified_reviews'])

X_text_df = pd.DataFrame(X_text.toarray())

""" Combine tokenized reviews with the main dataframe
 Hint: Use pd.concat() to join the dataframes

"""

df = df.drop(['verified_reviews'], axis=1)

df = pd.concat([df, X_text_df], axis=1)

df.head()

"""# Prepare data for modeling
 Split the data into features (X) and target (y)
The target variable is 'feedback'

"""

X = df.drop(['feedback'], axis=1)
y = df['feedback']
print(X.shape)
print(y.shape)

"""#Split the data into training and testing sets
Use train_test_split from sklearn.model_selection
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""#Train the Random Forest model
 Create and train the Random Forest model
 Use RandomForestClassifier from sklearn.ensemble

Train the Random Forest model
# Create and train the Random Forest model
 Use RandomForestClassifier from sklearn.ensemble
"""

rf_model = RandomForestClassifier(n_estimators=100)

# Convert all column names to strings to resolve TypeError
X_train.columns = X_train.columns.astype(str)
X_test.columns = X_test.columns.astype(str)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

"""# Evaluate the model
 Generate predictions and create confusion matrix
 Use the predict() method and confusion_matrix from sklearn.metrics

"""

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""Print classification report
 Use classification_report from sklearn.metrics
"""

print(classification_report(y_test, y_pred))

"""Feature Importance
 Visualize feature importance
 Access feature_importances_ attribute of the trained model
"""

train_acc = rf_model.score(X_train, y_train)
test_acc = rf_model.score(X_test, y_test)

print("Training Accuracy:", train_acc)
print("Testing Accuracy:", test_acc)

"""Make predictions on new data
 Create a function that takes a new review text, preprocesses it,
and uses the trained model to predict its sentiment
"""

if train_acc > test_acc:
    print("Model may be slightly overfitting")
else:
    print("Model is generalizing well")

def predict_sentiment(review):
    review = review.lower()

    review_vector = vectorizer.transform([review])

    prediction = rf_model.predict(review_vector)

    if prediction[0] == 1:
        return "Positive ✅"
    else:
        return "Negative ❌"